
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ci-pipeline-template
spec:
  params:
    - name: repo-url
    - name: run-sonarqube
      default: "false"
    - name: notification-webhook-url
      default: ""
  
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: tekton-trigger-listeners-run-
      spec:
        serviceAccountName: tekton-triggers-sa
        timeouts:
          pipeline: 45m0s
          tasks: 40m0s
          finally: 5m0s
        pipelineRef:
          name: tekton-trigger-listeners
        params:
          - name: repo-url
            value: $(tt.params.repo-url)
          - name: image-reference
            value: host.docker.internal:5000/sample-node-app
          - name: run-sonarqube
            value: $(tt.params.run-sonarqube)
          - name: notification-webhook-url
            value: $(tt.params.notification-webhook-url)
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes: [ReadWriteOnce]
                resources:
                  requests:
                    storage: 2Gi
          - name: docker-credentials
            secret:
              secretName: docker-credentials
          - name: cache
            persistentVolumeClaim:
              claimName: tekton-cache-pvc
