
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
spec:
  params:
    - name: repo-url
      value: $(body.repository.clone_url)
<<<<<<< HEAD
    
=======
    - name: image-reference
      value: muretimiriti/test1  # ← NO TAG! Just base name
>>>>>>> 196bd0142f4597d624cebade59a16e2c7280a3a2
    - name: run-sonarqube
      value: "false"
    
    # DO NOT include image-reference here
    # TriggerTemplate handles it with hardcoded value
