apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-read-run-
spec:
  serviceAccountName: tekton-triggers-sa
  timeouts:
    pipeline: 45m0s
    tasks: 40m0s
    finally: 5m0s
  pipelineRef:
    name: tekton-trigger-listeners
  podTemplate:
    securityContext:
      fsGroup: 65532
      
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: docker-credentials
    secret:
      secretName: docker-credentials
  - name: cache
    persistentVolumeClaim:
      claimName: tekton-cache-pvc
  - name: cosign-key
    secret:
      secretName: cosign-key
  params:
  - name: repo-url
    value: https://github.com/muretimiriti/Docker.git
  - name: image-reference
    value: host.docker.internal:5000/sample-node-app
  - name: run-sonarqube
    value: "false"
  - name: notification-webhook-url
    value: ""
  - name: integration-tests-strict
    value: "false"
  - name: run-integration-tests
    value: "false"
  - name: argocd-auto-deploy
    value: "true"
  - name: argocd-namespace
    value: "argocd"
  - name: argocd-app-name
    value: "tech-stack"
  - name: cosign-sign-enabled
    value: "true"
