apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: show-readme
spec:
  workspaces:
    - name: source
  steps:
    - name: debug
      image: alpine
      script: |
        set -e
        echo "PWD:"
        pwd
        echo "Workspace contents:"
        ls -la /workspace
        echo "Source contents:"
        ls -la /workspace/source
