apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-read
spec:
  description: |
    This pipeline clones a git repo and prints the README.

  params:
    - name: repo-url
      type: string
      description: The git repo URL to clone from
    - name: image-reference
      type: string
      description: The image reference to use for the show-readme task
  workspaces:
    - name: shared-data
      description: Workspace for cloned source code
    - name: docker-credentials
      description: Workspace for docker credentials
   

  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: shared-data
  

    - name: build-push
      runAfter: ["fetch-source"]
      taskRef:
       name: kaniko
      workspaces:
      - name: source
        workspace: shared-data
      - name: dockerconfig
        workspace: docker-credentials
      params:
      - name: IMAGE
        value: $(params.image-reference)
     
    
