apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-read
spec:
  description: |
    This pipeline clones a git repo and prints the README.

  params:
    - name: repo-url
      type: string
      description: The git repo URL to clone from

    - name: image-reference
      type: string
      description: The image reference to build and push

  workspaces:
    - name: shared-data
      description: Workspace for cloned source code

    - name: docker-credentials
      description: Workspace for docker credentials

  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: shared-data

    - name: debug-workspace
      runAfter:
        - fetch-source
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: list-workspace
            image: alpine
            script: |
              echo "Workspace contents:"
              ls -R /workspace
      workspaces:
        - name: source
          workspace: shared-data


    - name: sca-scan
      runAfter:
        - debug-workspace
      taskRef:
        name: trivy-sca-scan
      workspaces:
        - name: source
          workspace: shared-data 
      params:
        - name: IMAGE
          value: $(params.image-reference)
        - name: SEVERITY
          value: "HIGH,CRITICAL"
          
    - name: build-push
      runAfter:
        - debug-workspace
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: docker-credentials
      params:
        - name: IMAGE
          value: $(params.image-reference)
        - name:   CONTEXT
          value: my-app  
        - name: DOCKERFILE
          value: my-app/Dockerfile
