apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ci-pipeline-template
spec:
  params:
    - name: repo-url
    - name: image-reference

  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: clone-read-run-
      spec:
        pipelineRef:
          name: clone-read

        params:
          - name: repo-url
            value: $(tt.params.repo-url)
          - name: image-reference
            value: $(tt.params.image-reference)

        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 1Gi

          - name: docker-credentials
            secret:
              secretName: docker-credentials
