apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: sample-node-app-unsigned-image-temporary
  namespace: default
spec:
  background: true
  exceptions:
    - policyName: verify-sample-node-app-signature
      ruleNames:
        - verify-cosign-signature
  match:
    any:
      - resources:
          kinds:
            - Pod
          names:
            - sample-node-app-*
  conditions:
    all:
      - key: "{{ request.object.metadata.labels.\"security.kyverno.dev/allow-unsigned\" || '' }}"
        operator: Equals
        value: "true"
