apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-sample-node-app-signature
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: verify-cosign-signature
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "host.docker.internal:5000/sample-node-app*"
          mutateDigest: true
          required: true
          verifyDigest: true
          attestors:
            - entries:
                - keys:
                    publicKeys: |-
                      -----BEGIN PUBLIC KEY-----
                      REPLACE_WITH_COSIGN_PUBLIC_KEY
                      -----END PUBLIC KEY-----
