apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/sample-node-app
  - ../../platform/mongo
  - ../../platform/mongo-express
images:
  - name: host.docker.internal:5000/sample-node-app
    newName: host.docker.internal:5000/sample-node-app
    newTag: latest
