apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: docker-credentials
    creationPolicy: Owner
  data:
    - secretKey: config.json
      remoteRef:
        key: ci/docker-config
        property: config_json
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarqube-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sonarqube-credentials
    creationPolicy: Owner
  data:
    - secretKey: SONAR_HOST_URL
      remoteRef:
        key: ci/sonarqube
        property: host_url
    - secretKey: SONAR_TOKEN
      remoteRef:
        key: ci/sonarqube
        property: token
