apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-read
spec:
  description: |
    This pipeline clones a git repo and prints the README.

  params:
    - name: repo-url
      type: string
      description: The git repo URL to clone from

  workspaces:
    - name: shared-data
      description: Workspace for cloned source code

   

  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: shared-data
      

    - name: show-readme
      runAfter:
        - fetch-source
      taskRef:
        name: show-readme
      workspaces:
        - name: source
          workspace: shared-data
